import { Entypo } from "@expo/vector-icons";
import { Ionicons } from "@expo/vector-icons";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { SimpleLineIcons } from "@expo/vector-icons";

export const dark = {
  logo: require("../../assets/images/logo.png"),
  logoColor: "#32cd99",
  icon: <Entypo name="moon" size={36} color="white" />,
  menu: <SimpleLineIcons name="menu" size={24} color="white" />,
  image: require("../../assets/images/nightStar.png"),
  bg: "white",
  cardBg: "white",
  calender: "#252958",
  chart: "#BF2311",
  diary: "#456185",
  picture: "#274180",
  write: "#152F5E",
  share: "#456185",
  drawer: "white",
  front: "#152F5E",
  back: "#456185",
  font: "black",
  btn: "#456185",
  cardBorder: "#fff",
};

export const votanical = {
  logo: require("../../assets/images/logo.png"),
  logoColor: "#f23619",
  icon: <Ionicons name="leaf" size={36} color="white" />,
  menu: <SimpleLineIcons name="menu" size={24} color="white" />,
  image: require("../../assets/images/votanical.png"),
  bg: "white",
  cardBg: "white",
  calender: "#009775",
  chart: "#401D10",
  diary: "#005742",
  picture: "#003A40",
  write: "#004963",
  share: "#007D60",
  drawer: "white",
  front: "#005742",
  back: "#379947",
  font: "black",
  btn: "#008773",
  cardBorder: "#fff",
};

export const town = {
  logo: require("../../assets/images/logoTown.png"),
  logoColor: "#c97c91",
  icon: <Entypo name="home" size={36} color="white" />,
  menu: <SimpleLineIcons name="menu" size={24} color="white" />,
  image: require("../../assets/images/town.png"),
  bg: "white",
  cardBg: "white",
  calender: "#BFB7A8",
  chart: "#BD7388",
  diary: "#C0C4CC",
  picture: "#E0D290",
  write: "#D4937D",
  share: "#67A7C9",
  drawer: "white",
  front: "#BD7388",
  back: "#D4937D",
  font: "black",
  btn: "#D4937D",
  cardBorder: "#fff",
};

export const classic = {
  logo: require("../../assets/images/logoClassic.png"),
  logoColor: "#d6ad75",
  icon: <MaterialCommunityIcons name="ceiling-light" size={36} color="black" />,
  menu: <SimpleLineIcons name="menu" size={24} color="white" />,
  image: require("../../assets/images/classic.png"),
  bg: "white",
  cardBg: "white",
  calender: "#735938",
  chart: "#4C4B44",
  diary: "#D6AD74",
  picture: "#BDA653",
  write: "#574C26",
  share: "#A37A72",
  drawer: "white",
  front: "#735938",
  back: "#5A6D70",
  font: "black",
  btn: "#5A6D70",
  cardBorder: "#fff",
};

export const purple = {
  logo: require("../../assets/images/logoPurple.png"),
  logoColor: "#d9ba1f",
  icon: <Ionicons name="flower" size={36} color="white" />,
  menu: <SimpleLineIcons name="menu" size={24} color="white" />,
  image: require("../../assets/images/purple.png"),
  bg: "white",
  cardBg: "white",
  calender: "#4A1866",
  chart: "#660E4F",
  diary: "#994382",
  picture: "#80386C",
  write: "#4D420B",
  share: "#59274C",
  drawer: "white",
  front: "#59274C",
  back: "#4D420B",
  font: "black",
  btn: "#4D420B",
  cardBorder: "#fff",
};

export const block = {
  logo: require("../../assets/images/logoBlock.png"),
  logoColor: "#dbcfbf",
  icon: <MaterialCommunityIcons name="puzzle" size={36} color="white" />,
  menu: <SimpleLineIcons name="menu" size={24} color="white" />,
  image: require("../../assets/images/block.png"),
  bg: "white",
  cardBg: "white",
  calender: "#013480",
  chart: "#2A5E4A",
  diary: "#A66F2B",
  picture: "#7D7669",
  write: "#1D6A96",
  share: "#7592BD",
  drawer: "white",
  front: "#013480",
  back: "#A66F2B",
  font: "black",
  btn: "#A66F2B",
  cardBorder: "#fff",
};

export const pattern = {
  logo: require("../../assets/images/logoPattern.png"),
  logoColor: "#ebe0cc",
  icon: <Entypo name="houzz" size={36} color="white" />,
  menu: <SimpleLineIcons name="menu" size={24} color="white" />,
  image: require("../../assets/images/pattern.png"),
  bg: "white",
  cardBg: "white",
  calender: "#38341A",
  chart: "#B8B38D",
  diary: "#403945",
  picture: "#EBE0CC",
  write: "#5E5A52",
  share: "#63596B",
  drawer: "white",
  front: "#38341A",
  back: "#63596B",
  font: "black",
  btn: "#63596B",
  cardBorder: "#fff",
};

export const magazine = {
  logo: require("../../assets/images/logoMagazine.png"),
  logoColor: "#6eb5a8",
  icon: <Ionicons name="ios-newspaper-sharp" size={36} color="white" />,
  menu: <SimpleLineIcons name="menu" size={24} color="white" />,
  image: require("../../assets/images/magazine.png"),
  bg: "white",
  cardBg: "white",
  calender: "#422917",
  chart: "#C2B291",
  diary: "#8F6B24",
  picture: "#3F6961",
  write: "#A8683B",
  share: "#632806",
  drawer: "white",
  front: "#8F6B24",
  back: "#C2B291",
  font: "black",
  btn: "#C2B291",
  cardBorder: "#fff",
};

export const winter = {
  logo: require("../../assets/images/logoWinter.png"),
  logoColor: "#727370",
  icon: <Ionicons name="snow" size={36} color="black" />,
  menu: <SimpleLineIcons name="menu" size={24} color="black" />,
  image: require("../../assets/images/winter.png"),
  bg: "white",
  cardBg: "white",
  calender: "#B2B3AF",
  chart: "#727370",
  diary: "#D8D9D4",
  picture: "#B5C0CE",
  write: "#66654A",
  share: "#9492A6",
  drawer: "white",
  front: "#9492A6",
  back: "#9492A6",
  font: "black",
  btn: "#9492A6",
  cardBorder: "#000",
};
